---
- name: Copiar archivo sudoers prueba
  hosts: all  # O especifica un grupo como "webservers"
  become: yes  # Necesario para manipular /etc/sudoers.d/
  tasks:
    - name: Hacer backup del archivo existente
      ansible.builtin.copy:
        src: /etc/sudoers.d/sistemas
        dest: /etc/sudoers.d/sistemas.bak
        remote_src: yes
    - name: Copiar archivo prueba a los nodos
      ansible.builtin.copy:
        src: /etc/sudoers.d/sistemas
        dest: /etc/sudoers.d/sistemas_new
        owner: root
        group: root
        mode: "0440"  # Permisos seguros para sudoers
        remote_src: no  # Copia desde el controlador (AWX)
